INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Orson Welles', '1915', '1985', 'Actor', 'His father, Richard Head Welles, was a well-to-do inventor, his mother, Beatrice Welles, a beautiful concert pianist; Orson Welles was gifted in many arts(magic, piano, painting) as a child.', NULL, 'https://en.wikipedia.org/wiki/Orson_Welles#/media/File:Orson_Welles_1937_cr3-4.jpg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Herman J. Mankiewicz', '1897', '1953', 'Writer', ' Herman J. Mankiewicz, now known primarily as the man who co-wrote Citizen Kane (1941) with Hollywood greatest wunderkind, Orson Welles, was one of the highest-paid screenwriters in Hollywood and the head of Paramount screen-writing department in the late 1920s and early 1930s.', NULL,'https://en.wikipedia.org/wiki/Herman_J._Mankiewicz#/media/File:Herman-Mankiewicz.jpg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Pedro Pascal', '1975', NULL, 'Actor', 'Pedro Pascal is a Chilean-born actor famous for his role in Game of Thrones.', NULL, 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Pedro_Pascal_by_Gage_Skidmore.jpg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Bella Ramsey', '2003', NULL, 'Actress', 'Bella Ramsey made her debut in Game of Thrones and is playing the leading role in The Last of Us.', NULL, 'https://en.wikipedia.org/wiki/Bella_Ramsey#/media/File:Bella_Ramsey_at_the_2022_TIFF_Premiere_of_Catherine_Called_Birdy_(52358884151)_(cropped).jpg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Greta Gerwig', '1983', NULL, 'Director', 'Greta Gerwig is an American actress, playwright, screenwriter and director.', NULL, 'https://en.wikipedia.org/wiki/Greta_Gerwig#/media/File:Greta_Gerwig_Berlinale_2018.jpg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Margot Robbie', '1990', NULL, 'Actor', 'Margot Elise Robbie was born on July 2, 1990 in Dalby, Queensland, Australia to Scottish parents.', NULL, 'http://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRlkMgMM-I82HlvoKmqwNeu796H7MQg6U-3rEo01bp2S2mIBlKieIRaDtS_3sSHL5pI60EwumcVTFrKuBg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Bryan Cranston', '1956', NULL, 'Actor', 'Bryan Lee Cranston was born on March 7, 1956 in Hollywood, California, to a radio actress mother and an actor and amateur boxer father.', NULL, 'https://en.wikipedia.org/wiki/Bryan_Cranston#/media/File:Bryan_Cranston_at_the_2018_Berlin_Film_Festival_(2).jpg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Vince Gilligan', '1967', NULL, 'Producer', 'George Vincent Gilligan Jr. is an American writer, producer and director. He is known for his television work.', NULL, 'https://en.wikipedia.org/wiki/Vince_Gilligan#/media/File:Vince_Gilligan_by_Gage_Skidmore_3.jpg');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Anya Taylor Joy', '1996', NULL, 'Actor', 'Anya Taylor Joy is an actress born in 1996.', NULL, 'http://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRoSGjd-urReVE1wTZ9FVBUVS23OjoNbmjSAeNVpeJntq7Qe5q-risbXnpEpGxSqK5GTn-zeoOdt6T_DOw');
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId, photo_link) values('Aaron Horvath', '1980', NULL, 'Director', 'Aaron Horvath is an American director born in 1980.', NULL, 'https://en.wikipedia.org/wiki/Aaron_Horvath#/media/File:Aaron_Horvath_by_Gage_Skidmore.jpg');

