INSERT INTO Title(titleType,title,startYear,endYear,RuntimeMinutes,genres,link,views,avgRating) values('movie', 'Citizen Kane', '1941', NULL, 119, 'Drama|Mystery', 'https://www.youtube.com/watch?v=8dxh3lwdOFw', 0, 0);
INSERT INTO Title(titleType,title,startYear,endYear,RuntimeMinutes,genres,link,views,avgRating) values('TVseries', 'The Last of Us', '2023', NULL, 50, 'Action|Adventure|Drama', 'https://www.youtube.com/watch?v=uLtkt8BonwM', 0, 0);
INSERT INTO Title(titleType,title,startYear,endYear,RuntimeMinutes,genres,link,views,avgRating) values('movie', 'Barbie', '2023', NULL, NULL, 'Adventure|Comedy|Fantasy', 'https://www.youtube.com/watch?v=GRyt3Ov4zz0', 0, 0);
INSERT INTO Title(titleType,title,startYear,endYear,RuntimeMinutes,genres,link,views,avgRating) values('TVseries', 'Breaking Bad', '2008', '2013', 49, 'Crime|Drama|Thriller', 'https://www.youtube.com/watch?v=HhesaQXLuRY', 0, 0);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Orson Welles', '1915', '1985', 'Actor', 'His father, Richard Head Welles, was a well-to-do inventor, his mother, Beatrice Welles, a beautiful concert pianist; Orson Welles was gifted in many arts(magic, piano, painting) as a child.', NULL);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Herman J. Mankiewicz', '1897', '1953', 'Writer', ' Herman J. Mankiewicz, now known primarily as the man who co-wrote Citizen Kane (1941) with Hollywood greatest wunderkind, Orson Welles, was one of the highest-paid screenwriters in Hollywood and the head of Paramount screen-writing department in the late 1920s and early 1930s.', NULL);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Pedro Pascal', '1975', NULL, 'Actor', 'Pedro Pascal is a Chilean-born actor famous for his role in Game of Thrones.', NULL);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Bella Ramsey', '2003', NULL, 'Actress', 'Bella Ramsey made her debut in Game of Thrones and is playing the leading role in The Last of Us.', NULL);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Greta Gerwig', '1983', NULL, 'Director', 'Greta Gerwig is an American actress, playwright, screenwriter and director.', NULL);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Margot Robbie', '1990', NULL, 'Actor', 'Margot Elise Robbie was born on July 2, 1990 in Dalby, Queensland, Australia to Scottish parents.', NULL);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Bryan Cranston', '1956', NULL, 'Actor', 'Bryan Lee Cranston was born on March 7, 1956 in Hollywood, California, to a radio actress mother and an actor and amateur boxer father.', NULL);
INSERT INTO Celebrities(primaryName, birthYear, deathYear, primaryProfession, Intro, userId) values('Vince Gilligan', '1967', NULL, 'Producer', 'George Vincent Gilligan Jr. is an American writer, producer and director. He is known for his television work.', NULL);
INSERT INTO titleCast values(1,1, 'Actor', 'Kane');
INSERT INTO titleCast values(1,1, 'Director', 'NA');
INSERT INTO titleCast values(1,2, 'Writer', 'NA');
INSERT INTO titleCast values(2,3, 'Actor', 'Joel Miller');
INSERT INTO titleCast values(2,4, 'Actor', 'Ellie Williams');
INSERT INTO titleCast values(3,5, 'Actor', 'Barbie');
INSERT INTO titleCast values(3,6, 'Director', 'Greta Gerwig');
INSERT INTO titleCast values(4,7, 'Actor', 'Walter White');
INSERT INTO titleCast values(4,8, 'Creator', 'NA');
INSERT INTO titleCast values(4,8, 'Writer', 'NA');
INSERT INTO Awards values(DEFAULT, 'Oscar', 'Best Original Screenplay', '1942', 1);
INSERT INTO Awards values(DEFAULT, 'Emmy', 'Outstanding Drama Series', '2014', 4);
INSERT INTO Awards values(DEFAULT, 'Emmy', 'Outstanding Drama Series', '2013', 4);
INSERT INTO celebAwards values(8, 2);
INSERT INTO celebAwards values(8, 3);
INSERT INTO celebAwards values(1, 1);
INSERT INTO celebAwards values(2, 1);
